//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherOfGujarat.GetDataServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetDataServiceRef.retriveinformationSoap")]
    public interface retriveinformationSoap {
        
        // CODEGEN: Generating message contract since element name GetDataDistrictResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataDistrict", ReplyAction="*")]
        WeatherOfGujarat.GetDataServiceRef.GetDataDistrictResponse GetDataDistrict(WeatherOfGujarat.GetDataServiceRef.GetDataDistrictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataDistrict", ReplyAction="*")]
        System.Threading.Tasks.Task<WeatherOfGujarat.GetDataServiceRef.GetDataDistrictResponse> GetDataDistrictAsync(WeatherOfGujarat.GetDataServiceRef.GetDataDistrictRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataDistrictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataDistrict", Namespace="http://tempuri.org/", Order=0)]
        public WeatherOfGujarat.GetDataServiceRef.GetDataDistrictRequestBody Body;
        
        public GetDataDistrictRequest() {
        }
        
        public GetDataDistrictRequest(WeatherOfGujarat.GetDataServiceRef.GetDataDistrictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataDistrictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int districtId;
        
        public GetDataDistrictRequestBody() {
        }
        
        public GetDataDistrictRequestBody(int districtId) {
            this.districtId = districtId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataDistrictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataDistrictResponse", Namespace="http://tempuri.org/", Order=0)]
        public WeatherOfGujarat.GetDataServiceRef.GetDataDistrictResponseBody Body;
        
        public GetDataDistrictResponse() {
        }
        
        public GetDataDistrictResponse(WeatherOfGujarat.GetDataServiceRef.GetDataDistrictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataDistrictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataDistrictResult;
        
        public GetDataDistrictResponseBody() {
        }
        
        public GetDataDistrictResponseBody(string GetDataDistrictResult) {
            this.GetDataDistrictResult = GetDataDistrictResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface retriveinformationSoapChannel : WeatherOfGujarat.GetDataServiceRef.retriveinformationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class retriveinformationSoapClient : System.ServiceModel.ClientBase<WeatherOfGujarat.GetDataServiceRef.retriveinformationSoap>, WeatherOfGujarat.GetDataServiceRef.retriveinformationSoap {
        
        public retriveinformationSoapClient() {
        }
        
        public retriveinformationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public retriveinformationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public retriveinformationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public retriveinformationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WeatherOfGujarat.GetDataServiceRef.GetDataDistrictResponse WeatherOfGujarat.GetDataServiceRef.retriveinformationSoap.GetDataDistrict(WeatherOfGujarat.GetDataServiceRef.GetDataDistrictRequest request) {
            return base.Channel.GetDataDistrict(request);
        }
        
        public string GetDataDistrict(int districtId) {
            WeatherOfGujarat.GetDataServiceRef.GetDataDistrictRequest inValue = new WeatherOfGujarat.GetDataServiceRef.GetDataDistrictRequest();
            inValue.Body = new WeatherOfGujarat.GetDataServiceRef.GetDataDistrictRequestBody();
            inValue.Body.districtId = districtId;
            WeatherOfGujarat.GetDataServiceRef.GetDataDistrictResponse retVal = ((WeatherOfGujarat.GetDataServiceRef.retriveinformationSoap)(this)).GetDataDistrict(inValue);
            return retVal.Body.GetDataDistrictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WeatherOfGujarat.GetDataServiceRef.GetDataDistrictResponse> WeatherOfGujarat.GetDataServiceRef.retriveinformationSoap.GetDataDistrictAsync(WeatherOfGujarat.GetDataServiceRef.GetDataDistrictRequest request) {
            return base.Channel.GetDataDistrictAsync(request);
        }
        
        public System.Threading.Tasks.Task<WeatherOfGujarat.GetDataServiceRef.GetDataDistrictResponse> GetDataDistrictAsync(int districtId) {
            WeatherOfGujarat.GetDataServiceRef.GetDataDistrictRequest inValue = new WeatherOfGujarat.GetDataServiceRef.GetDataDistrictRequest();
            inValue.Body = new WeatherOfGujarat.GetDataServiceRef.GetDataDistrictRequestBody();
            inValue.Body.districtId = districtId;
            return ((WeatherOfGujarat.GetDataServiceRef.retriveinformationSoap)(this)).GetDataDistrictAsync(inValue);
        }
    }
}
